# Generated by Django 6.0.6 on 2026-06-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='titulo',
            field=models.CharField(default='Aviso', max_length=100),
        ),
    ]
